---
- name: Install MariaDB Server 10
  apt:
    name: mariadb-server
    install_recommends: no
    state: present
  notify: restart mysql

- name: Enable service
  systemd:
    name: mysqld
    enabled: yes

- name: Add Python MySQL support
  apt:
    name: python3-pymysql
    install_recommends: no
    state: present

- name: Change root user password on first run
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
  loop:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  no_log: true

- name: delete anonymous MySQL server user for {{ ansible_hostname }}
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: ""
    host: "{{ item }}"
    state: "absent"
  loop:
    - "{{ ansible_hostname }}"
    - ""
  no_log: true

- name: remove the MySQL test database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: test
    state: absent
